name: Continuous Integration

on:
  push:
    branches: [base]
  pull_request:
    branches: [base]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: black linter
        run: |
          black . --check
      - name: Linting with pylint
        run: |
          pylint tensornetwork
      - name: Test with pytest
        run: |
          pytest --cov=./
      - name: Upload coverage to Codecov
        if: matrix.oython-version == '3.8'
        uses: codecov/codecov-action@v2
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: setup build
        run: |
          python3 setup.py build
